/**
 * \file
 * Hardware configuration file (PC or AVR). Tells the autogenerated
 * register files whether they are being compiled on PC or AVR, typically 
 * so that constant arrays can be placed in flash memory on the latter.
 * 
 */

#ifndef __HWCONFIG_H
#define __HWCONFIG_H

#define PC 1

#endif /* __HWCONFIG_H */
